# Generated by Django 3.2.23 on 2024-02-17 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Cassava', 'Cassava 🍠'), ('Maize', 'Maize 🌽'), ('Rice', 'Rice 🍚')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('crops', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('other_location', models.CharField(max_length=255)),
                ('location_coordinates', models.CharField(max_length=255)),
                ('land_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_crops', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_for_recipients', models.BooleanField(default=False)),
                ('deleted_by_sender', models.BooleanField(default=False)),
                ('deleted_by_field_agent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_employment', models.DateField(blank=True, null=True)),
                ('casual_labourer', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='workers_photos/')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_supplied', models.DateField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='district',
            field=models.TextField(blank=True, choices=[('', 'Select District'), ('Lango', 'Lango'), ('Teso', 'Teso'), ('Abim', 'Abim'), ('Nakaseke', 'Nakaseke'), ('Other', 'Other')], null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='farmer_orgs',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_checked_message',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='other_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_belongs_to_user',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='main.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_replies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_message_ids', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FarmVisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_visits', to='main.farm')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmVisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('farm_visit_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farm_visit_report', to='main.farmvisitrequest')),
            ],
        ),
        migrations.CreateModel(
            name='FarmProduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_planted', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bags_harvested', models.IntegerField(blank=True, null=True)),
                ('amount_sold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_kgs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_amount_tonnes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('market', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='farm_produce', to='main.farm')),
            ],
        ),
        migrations.CreateModel(
            name='FarmPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='farm_photos/')),
                ('description', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_photos', to='main.farm')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmingDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_planting', models.DateField(blank=True, null=True)),
                ('date_ploughing', models.DateField(blank=True, null=True)),
                ('date_weeding', models.DateField(blank=True, null=True)),
                ('date_harvesting', models.DateField(blank=True, null=True)),
                ('date_fertilizer_application', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='farming_dates', to='main.farm')),
            ],
        ),
        migrations.CreateModel(
            name='FarmingCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_fertilizer_application', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_planting', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_ploughing', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_weeding', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_harvesting', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transport_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='farming_costs', to='main.farm')),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='farm_labourers',
            field=models.ManyToManyField(blank=True, related_name='farms_labourer', to='main.Person'),
        ),
        migrations.AddField(
            model_name='farm',
            name='resources_supplied',
            field=models.ManyToManyField(blank=True, related_name='farms', to='main.Resource'),
        ),
        migrations.AddField(
            model_name='farm',
            name='staff_contacts',
            field=models.ManyToManyField(blank=True, related_name='farms_staff', to='main.Person'),
        ),
        migrations.AddField(
            model_name='farm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
