# Generated by Django 3.2.23 on 2024-02-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240217_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(choices=[('Cassava', 'Cassava 🍠'), ('Maize', 'Maize 🌽'), ('Rice', 'Rice 🍚'), ('wheat', 'wheat🌾'), ('coconut', 'coconut🌴'), ('cashew', 'cashew🍐'), ('peanut', 'peanut🥜')], max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='district',
            field=models.TextField(blank=True, choices=[('', 'Select District'), ('Srikakulam', 'Srikakulam'), ('Visakhapatnam', 'Visakhapatnam'), ('Guntur', 'Guntur'), ('Nellore', 'Nellore'), ('Other', 'Other')], null=True),
        ),
    ]
