# Generated by Django 3.2.23 on 2024-02-23 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20240223_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
