# Generated by Django 3.2.23 on 2024-02-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20240223_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduler',
            old_name='worker',
            new_name='worker_name',
        ),
    ]
