# Generated by Django 3.2.23 on 2024-03-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_invoice_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='services_required',
            field=models.TextField(blank=True, choices=[('', 'Select Service'), ('Pollination', 'Pollination'), ('Sowing', 'Sowing'), ('Stem Covering', 'Stem Covering'), ('Irrigation', 'Irrigation'), ('Pest Control', 'Pest Control'), ('Planting', 'Planting'), ('Drainage', 'Irrigation'), ('Spraying', 'Irrigation'), ('Manuring', 'Manuring'), ('Forking', 'Forking'), ('Harvesting', 'Harvesting'), ('Fertigation', 'Fertigation'), ('Other', 'Other')], null=True),
        ),
    ]
