# Generated by Django 3.2.23 on 2024-03-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_farm_services_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='other_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
