# Generated by Django 3.2.23 on 2024-03-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_farm_other_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='farm',
            name='services_required',
        ),
        migrations.AddField(
            model_name='farm',
            name='services_required',
            field=models.ManyToManyField(blank=True, to='main.Service'),
        ),
    ]
