# Generated by Django 3.2.23 on 2024-03-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20240305_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='services_required',
        ),
        migrations.AddField(
            model_name='farm',
            name='services_required',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
