# Generated by Django 4.2.11 on 2024-03-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_paypal_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
            ],
        ),
    ]
